version: '3.8'

services:
  next:
    image: registry.bykollab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}.rule=Host(`${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}.do.bykollab.com`)"
        - "traefik.http.routers.${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}.entrypoints=https"
        - "traefik.http.routers.${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}.tls"
        - "traefik.http.services.${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}.loadbalancer.server.port=3000"

networks:
  default:
    name: web
    external: true
